parroty/excoveralls

README.md

Your library is very helpful and I use it in my projects.  I wanted to help clean up the documentation and the syntax a bit.  Keep up the great work!

Typo Fixed and Syntax Clarity

---

README.md

Just updating the install instruction. Thanks for the neat stuff

Update install version in deps

---

lib/excoveralls/circle.ex
lib/excoveralls/conf_server.ex
lib/excoveralls/html.ex
lib/excoveralls/html/view.ex
lib/excoveralls/local.ex
lib/excoveralls/path_reader.ex
lib/excoveralls/semaphore.ex
lib/excoveralls/settings.ex
lib/excoveralls/travis.ex
mix.exs

Use parenthesis to remove the ambiguity with variables.

Fix Elixir 1.4 warnings

---

lib/excoveralls.ex
lib/excoveralls/json.ex
lib/mix/tasks.ex
mix.exs
test/excoveralls_test.exs
test/json_test.exs
test/mix/tasks_test.exs

add json task (for Codecov.io support)

---

README.md

* say ignore once in the exclude files section so people like me that are just looking for that can find it
* smaller grammar and spelling corrections

Improve  coveralls.json section a bit

---

README.md

h-tag changed with ff52a54b0241cf74db69f7e230acaccf5a097b99 
just fixed the link :)

fix(readme): fix broken link for mix coveralls.post

---

.travis.yml
lib/excoveralls.ex
lib/excoveralls/circle.ex
lib/excoveralls/json.ex
lib/excoveralls/post.ex
lib/excoveralls/semaphore.ex
lib/excoveralls/settings.ex
lib/excoveralls/travis.ex
mix.exs
mix.lock
test/circle_test.exs
test/json_test.exs
test/post_test.exs
test/semaphore_test.exs
test/travis_test.exs

Jason is the new de-facto library that is used in Ecto and Phoenix,
ExCoveralls was the only library that added JSX dependency. 
Jason is blazing fast too.

Replace JSX with Jason

---

lib/templates/html/htmlcov/coverage.html.eex
test/html_test.exs

Add meta tag for utf-8 charset to coverage.html

---

README.md

Updated the version number, keep up the good work

Fixed version number

---

README.md

I think this got separated by mistake in #154

Move sempahore README text back toghether

---

lib/excoveralls/html/view.ex
lib/templates/html/htmlcov/_style.html.eex
lib/templates/html/htmlcov/coverage.html.eex
test/html/view_test.exs
test/html_test.exs

Gray color for percent number for file with 0 relevant lines in html view

color for case with 0 relevant lines

---

README.md

fix #161 
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

Update readme on umbrella application

---

lib/mix/tasks.ex

Nasty mistake introduced in #158 
@parroty any ideas on how we can test this in a good way?

Fix #160 - make sure analyze_sub_apps gets called

---

README.md
lib/excoveralls/html.ex
lib/excoveralls/json.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
mix.lock
test/html_test.exs
test/json_test.exs

Output dir

---

README.md

Fix broken link to "Ignore Lines" header in readme.md

Repaired broken "Ignore Lines" header

---

README.md

Fix compile warning in README

---

README.md

The committer option was miss-spelled.

Fix typo committer option

---

lib/excoveralls/semaphore.ex
test/semaphore_test.exs

This should fix #179.
This is a breaking change for people who haven't migrated to the new Semaphore.

Updated Semaphore variables

---

.github/workflows/main.yml
README.md
lib/excoveralls.ex
lib/excoveralls/github.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
test/excoveralls_test.exs
test/fixtures/github_event.json
test/github_test.exs
test/mix/tasks_test.exs

This add the ability to upload coverage from GitHub Actions.
Example: https://github.com/mijailr/actions_sample
Related to #206  #202 #201

Add support for GitHub Actions

---

README.md
lib/excoveralls/local.ex
lib/excoveralls/settings.ex
test/html_test.exs
test/json_test.exs
test/local_test.exs

Solves https://github.com/parroty/excoveralls/issues/148

Add terminal option to hide file coverage list

---

.github/workflows/tests.yml

The old actions/setup-elixir action repo has been archived, this is the new official setup-elixir action repo.

the official elixir github actions repo is here now

---

README.md

💁 The previous URL was invalid.

Docs: Update license URL

---

lib/templates/html/htmlcov/coverage.html.eex

- h2 tag was closed with h1 tag, triggering my HTML linter
Fixes #258

Fix small HTML error

---

README.md
lib/excoveralls.ex
lib/excoveralls/lcov.ex
lib/mix/tasks.ex
test/lcov_test.exs

Re-pull request for https://github.com/parroty/excoveralls/pull/261

feat: minimum support for lcov (re)

---

lib/excoveralls/poster.ex

My bad.See https://github.com/parroty/excoveralls/pull/311#discussion_r1288142340

Remove erroneous line in ExCoveralls.poster
