parroty/excoveralls

README.md

Provides color when piping the output of mix coveralls.detail to the "less" pager

pass -R option to less for color

---

lib/excoveralls/post.ex
lib/excoveralls/poster.ex
lib/mix/tasks.ex
test/mix/tasks_test.exs
test/post_test.exs

Hi,
I am currently working on a small project with an API compatible with Coveralls,
and I would like to be able to customize the endpoint to be able to change https://coveralls.io
when posting the stats.
I made a small change to read `COVERALLS_ENDPOINT` for the `mix coveralls.post` task.
The behavior stays the same if the environment variable is not present.
Thanks.

Allow to override coveralls endpoint.

---

README.md
lib/excoveralls/post.ex
lib/mix/tasks.ex
mix.lock
test/mix/tasks_test.exs
test/post_test.exs

When debugging an [issue](https://github.com/lemurheavy/coveralls-public/issues/672#issuecomment-159724697) with @dokie I noticed that none of his builds were coming through from CircleCi with a commit SHA. When sending coverage data to Coveralls from Travis it's ok to omit that because we query their API to pull the commit info. But for other CI's it needs to be specified explicitly.
I've added SHA as the `-s` parameter here, but this could be refactored to pull git info directly from the environment. Here's how we do that in [coveralls-ruby](https://github.com/lemurheavy/coveralls-ruby/blob/master/lib/coveralls/configuration.rb#L138):
```ruby
hash[:head] = {
:id => ENV.fetch("GIT_ID", `git log -1 --pretty=format:'%H'`),
:author_name => ENV.fetch("GIT_AUTHOR_NAME", `git log -1 …
```

added --sha parameter for non-Travis compatibility

---

README.md
lib/excoveralls/task/util.ex
lib/excoveralls/travis.ex
test/mix/tasks_test.exs
test/travis_test.exs

We're using travis pro and I had to make a few tweaks to get it to work.

Support travis pro.

---

README.md
lib/excoveralls.ex
lib/excoveralls/circle.ex
lib/mix/tasks.ex
test/circle_test.exs
test/excoveralls_test.exs
test/mix/tasks_test.exs

Adds a CircleCI task for integration without having to use the more limited `post` task.
- added `service_number` to align CircleCI build numbers with coveralls build numbers
- added `service_pull_request` to provide github PR link id
- added `--parallel` flag to allow multi-container builds
- extracts message from git log

Add CircleCI integration

---

README.md

Hi,
thanks for providing this library first of all! I just integrated `excoveralls` in a project and noticed the instructions for setting up code coverage reporting on Travis CI are a little outdated.
Elixir is now available as it's own language (in Beta, but works flawlessly) on Travis, which we can make use of to simplify the configuration file.
I added a note to explicitly set `MIX_ENV=test` via Travis' config file to prevent users from experiencing the `** (Mix) The task "coveralls.travis" could not be found` error.
Executing `mix do deps.get, compile` manually isn't needed anymore, it's part of the default `before_script` build step, see https://docs.travis-ci.com/user/languages/elixir#Default-commands. 
To verify this is working, here's the new `.travis.yml` config in action: …

Improve instructions for Travis CI

---

lib/excoveralls.ex
lib/excoveralls/stats.ex
lib/excoveralls/sub_apps.ex
lib/mix/tasks.ex
test/mix/tasks_test.exs
test/stats_test.exs
test/sub_apps_test.exs

Ordering sub app paths to force the longest one to be matched first.
Also grabbing the apps path from the mix config so it will be appended
when building the stats path.
Paths to the source files in subapps would not properly reflect their
location in the directory. If a subapp's name contained another it was
possible for it to not have it's files listed correctly.
Given a project structure similar to:
```
umbrella/
apps/
myapp
myapp_web
```
Where `myapp_web` has a dependency on `myapp` causing it to appear
after `myapp` in the results of `Mix.Dep.Umbrella.loaded`. This causes
all file paths reported to begin with `myapp`. Additionally the
`apps/` directory would not be prepended to allow coveralls.io to find
the source file.
The report would show these files:
```
myapp/lib/mod.ex …
```

fix umbrella source paths in report

---

lib/excoveralls/cover.ex

This PR replaces `__info__` with `module_info` which exists in both Elixir compiled modules as well as pure Erlang ones. As a result, if a mix project has `.erl` files, they will also be included in the cover analysis.

use module_info instead of __info__

---

README.md
coveralls.json
lib/conf/coveralls.json
lib/excoveralls/html.ex
lib/excoveralls/local.ex
lib/excoveralls/settings.ex
lib/excoveralls/stats.ex
test/fixtures/no_relevant_lines_are_covered.json
test/fixtures/no_relevant_lines_not_covered.json
test/html_test.exs
test/local_test.exs
test/settings_test.exs
test/stats_test.exs

This pull request adds support for a new option in the `coveralls.json` file inside the `coverage_options` key: `minimum_coverage` (defaults to zero). When the user adds a value in this option, running `mix coveralls` or `mix coveralls.html` will exit with a status code of 1 if total coverage falls below that threshold. This is useful for stopping CI pipelines with tight coverage requirements.
I noticed the `Html` module had some totalization of stats in it, so those were moved into `Stats`. That has significantly cleaned up `Html`. There are many calculations for individual files still going on in the `Local` module, but I chose not to refactor those for now. We could tackle that on a later PR.
Let me know what you think! Cheers.

Add support for minimum coverage

---

lib/mix/tasks.ex
test/mix/tasks_test.exs

For example --no-start
I was unable to pass `--no-start` down to the mix test task. This PR attempt to fix that. Feedback is much appreciated.

Make sure additional args can be passed to mix

---

README.md
lib/excoveralls.ex
lib/excoveralls/semaphore.ex
lib/mix/tasks.ex
test/excoveralls_test.exs
test/mix/tasks_test.exs
test/semaphore_test.exs

Add Support to SemaphoreCI

---

.travis.yml
lib/mix/tasks.ex
mix.lock
test/mix/tasks_test.exs

Fixes tests error with following message, which was caused by directly mocking Mix.Task.run.
```
% mix test test/mix/tasks_test.exs
** (EXIT from #PID<0.70.0>) killed
```

Fix tests error with elixir 1.3.2

---

lib/mix/tasks.ex
test/mix/tasks_test.exs

like `--include remote`, but not including ExCoveralls specific args that cover won’t understand.
fixes #46

pass through args to cover

---

lib/excoveralls/html.ex
lib/excoveralls/html/view.ex
lib/excoveralls/json.ex
lib/excoveralls/local.ex
lib/excoveralls/settings.ex
lib/excoveralls/stat_server.ex
lib/mix/tasks.ex
mix.exs

This PR removes the deprecation for Dict Usage in favor of Map.
Dict has been deprecated since Elixir 1.2 as Erlang 1.8 got a huge performance boost on maps.
Map is now the favored data structure for maps.
See :
https://github.com/elixir-lang/elixir/blob/v1.2.0/CHANGELOG.md#erlang-18-support
https://hexdocs.pm/elixir/Map.html
Note : Map was officially deprecated in elixir 1.2.
I'm bumping the compatible version as it may fail on elixir 1.0 / 1.1 (these release are over 2-3 years old).
Thanks!

Favor MapSet over Dict (elixir 1.2 deprecations)

---

README.md
lib/mix/tasks.ex

Elixir provides the ability to use @preferred_cli_env directly on the task since version v1.3.0. This PR declares those attributes by default.
Keep in mind that:
1. This won't work for Elixir versions earlier than v1.3.0. If you still support them, you may want to add the line about preferred_cli_env back to the README
2. The README will be outdated as soon as this is merged, so you may want to consider a new release
Thank you! :heart:

Use @preferred_cli_env

---

lib/mix/tasks.ex

I have a build pipeline for a work project that builds a docker image with my app compiled with `MIX_ENV=prod`. Later on I run all the tests against this image. This prevented me from using `excoveralls` because it would try to set my `Mix.env(:test)` for my unit tests. Just skipping this call lets my tests run as expected (both `mix coveralls` and `mix test` run under the `prod` env).
I think this should be okay to do since you documentation in your project to tell people to use a preferred CLI env of `test`, so their unit tests will usually run with `Mix.env == :test`, but it will allow other use-cases like mine to work as well.
Maybe there's a reason this needs to be set? I tried searching the git history, but it looks like this has been here from the beginning of the projects so I …

do not force mix env when running tests

---

lib/excoveralls/stats.ex

In some cases the call to erlang's cover.analyse/3 will return more than
one result for the same line. Usually the coverage count is the same,
but in some cases (e.g. with schema definitions in an Ecto model) the
coverage count can alternate between different values, like 1 and 0, and
the line might be marked as covered or not depending on the order of
these results.
Investigations did not lead to a definite answer as to why this is
happening, but with this fix we will at least take the greatest coverage
count, instead of the latest, as the value for our report.
Fixes #84

Take the highest coverage count for a single line

---

lib/excoveralls/html/view.ex
lib/templates/html/htmlcov/coverage.html.eex

**Problem:**
I wanted to set a custom template. This didn't work. I copied the template directory from the library and changes the contents. Strangely only the _script.html.eex and _style.html.eex customizations worked.
**Solution:**
After debugging, i found the issue.
The main template function `render` for the coverage.html.eex is evaluated during compile time. So template_path is only ignored for this template.  
In the patch I used `EEx.eval_file`. This is also used for the partial function.

Fix html template is ignoring template_path from options

---

lib/templates/html/htmlcov/coverage.html.eex

When using Elixir 1.5, generating HTML coverage reports caused some warnings to be thrown due to changes in how the `<%` and `<%=` tags work. This PR fixes those warnings (and appears to generate the same output).

Fix EEx template warnings

---

lib/excoveralls/cover.ex
lib/excoveralls/stats.ex

This uses conditional compilation á la [decimal](https://github.com/ericmj/decimal/blob/master/lib/decimal.ex#L1475-L1480) to stay compatible while silence the warning.
https://hexdocs.pm/elixir/deprecations.html

Fix to_char_list -> to_charlist deprecation

---

lib/mix/tasks.ex
test/mix/tasks_test.exs

that coverage is being run against an umbrella app and only posts
to coveralls.io once all sub-applications have been analysed
Fixes #76 
Prior to this change, `Poster.execute/2` was getting called after every sub application's coverage was calculated. Now, it only gets called once at the end of the last sub application's coverage run.
The excoveralls.post.json file that is sent to coveralls.io contains all of the files from all sub-applications and the reported coverage number in coveralls.io now matches that produced in the summary line when running:
`mix coveralls --umbrella`

Changes the behavior of mix coveralls.post so that it recognizes

---

lib/excoveralls/settings.ex

I was looking for a way to use my own custom config and templates for all my projects.
To accomplish this I've changed the custom_file to first check if  ~/.excoveralls/coveralls.json  exists and if so, use that, if not check if coveralls.json exists in the project, otherwise use the default one from the package.
In my case I've created a custom template which I store in ~/.excoveralls/templates/html/htmlcov which uses a custom theme, highlight.js, firacode and hides all files in preview that are already 100% covered.
my config looks like:
```json
{
"coverage_options": {
"template_path": "~/.excoveralls/templates/html/htmlcov"
}
}
```
example output:
If you are interested in the template, you can find it here : https://github.com/smeevil/excoveralls_dark_template
Hopefully you'll find …

added support for ~/.excoversalls/coveralls.json

---

lib/excoveralls/local.ex
lib/mix/tasks.ex

Still would like to get some tests around it as well as update the docs/help banner
Adds a `--sort` option to the local runner. The option can take one or more fields and with explicit sort direction. Sorting is stable and prioritizes the first sort option
Ex:
```
$ mix coveralls --sort cov
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% lib/excoveralls/exceptions.ex                  11        0        0
100.0% lib/excoveralls/html/safe.ex                   28        2        0
100.0% lib/excoveralls/path_reader.ex                 20        2        0
100.0% lib/excoveralls/stat_server.ex                 21        4        0
100.0% lib/excoveralls/stop_words.ex                  37        7        0
100.0% lib/excoveralls/sub_apps.ex …
```

add --sort option to Local runner

---

lib/excoveralls/settings.ex
test/fixtures/dotfile.json
test/settings_test.exs
test/stats_test.exs

Hi,
So I'm using the dot file settings quite a lot to customise the report template and to add some global ignores. Working with other projects I found that it would be _very_ useful if the coveralls.json defined in the project would merge its settings with those of the users dot file one. This way the project defined one always overrules the dot file one if duplicate keys are defined. 
I've also updated the test to accommodate for the custom dot file. my previous patch worked as long as you had no dot file while running the tests. its now integrated with the other mocks.
Please let me know if you agree with this, and if the purpose is clear :)
Gerard

merge dot file settings and project settings

---

mix.exs
mix.lock

Fixes #107
See:
* discussion in https://github.com/eproxus/meck/issues/179
* fix in https://github.com/eproxus/meck/pull/180

Bump meck to 0.8.9

---

README.md

With links to documentation for uploading coverage reports to Codecov and Code Climate.
Refs #62 #119 
/cc @nathany @stevepeak @ale7714 @blatyo

Add documentation for mix coveralls.json

---

coveralls.json
lib/excoveralls/cover.ex
mix.exs
test/cover_test.exs
test/fixtures/test_missing.ex

This change introduces a check in the `Cover` module to verify the related source for a compiled module is still present. Missing source files are a common issue for CI builds with cached build paths, where later commits have removed or renamed a file.
If the source is not present, the module is skipped in stats reporting and a warning is logged. This ensures previously compiled modules that may no longer exist will not cause the build to exit with an error status, yet still provide visibility on missing modules.
Resolves: #55

Ensure missing source from dirty build dir is not reported

---

lib/excoveralls/local.ex
lib/excoveralls/stats.ex
lib/excoveralls/stop_words.ex
test/html_test.exs
test/local_test.exs
test/stats_test.exs
test/stop_words_test.exs

This change covers all the tests and areas I could find affected by https://github.com/parroty/excoveralls/commit/c1fdf4142f5e86094fa7512f5b2675649fa1f9f4.
Resolves #140

Fix umbrella stats and make source consistent

---

lib/mix/tasks.ex

this gets rid of warning on elixir 1.7
```
warning: not passing the :switches or :strict option to OptionParser is deprecated
(elixir) lib/option_parser.ex:562: OptionParser.build_config/1
(elixir) lib/option_parser.ex:197: OptionParser.parse/2
lib/mix/tasks.ex:18: Mix.Tasks.Coveralls.run/1
(mix) lib/mix/task.ex:316: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

pass switches to OptionParser.parse opts

---

README.md
lib/excoveralls.ex
lib/excoveralls/drone.ex
lib/mix/tasks.ex
test/drone_test.exs
test/excoveralls_test.exs

Add dedicated mix task to send coveralls reports from drone CI:
~~~
mix coveralls.drone
~~~
Still investigating if drone CI exposes github account URL. For now `committer` contains only user name.
BTW, how all these attributes (committer, build nr, pr nr) are sent by travis task? I could not find it in the code?

Add support for drone CI

---

lib/excoveralls/circle.ex

* `CIRCLE_WORKFLOW_WORKSPACE_ID` is the same when "Rerun failed job" is done while `CIRCLE_WORKFLOW_ID` changes, so use `CIRCLE_WORKFLOW_WORKSPACE_ID` for `service_number`, so that the results from the original and rerun are combined.  Use `CIRCLE_BUILD_NUM` for `service_number` either in or out of Workflows.
This appears to match the usage of `service_number` and `service_job_id` in
https://github.com/lemurheavy/coveralls-ruby/commit/cf20b3a3242483b7b5bf7fbdf149008aa0a20541, which added parallel support for the older, parallel-in-1-job system to coveralls-ruby - `service_job_id` varies over the parallel things while
`service_number` must be the same across all parallel siblings.
A workflow using `--parallel` and a manual `done` single with `curl` call can be seen …

Parallel support for separate CircleCI Workflow jobs

---

lib/mix/tasks.ex
test/mix/tasks_test.exs

This is an attempt at fixing #156 by making sure that extra arguments for the `post` task makes it down to mix.
Could probably be done nicer with some bigger changes.

Fix #156 - argument passing for post task

---

lib/excoveralls/poster.ex
test/poster_test.exs

Our JSON payload for coveralls seems to be quite substantial and we're suffering from timeouts which block our CI workflow. This PR gzips the payload before sending as the coveralls API supports this and loosens the timeout from 5sec to 10sec.

GZIP the JSON for coveralls and loosen the timeout

---

lib/excoveralls/poster.ex
test/poster_test.exs

Small fix for #112 
Might make more sense with an option to control this, but I figured this should be a good default for most cases.

Do not fail due to timeout from poster

---

lib/mix/tasks.ex
test/mix/tasks_test.exs

For the `mix coveralls.post` task, the `name` switch was missing and resulted in an error. 
Besides that, the `committer` switch was misspelled. So we fixed it also.

Add missing `name` switch, also fixed `committer` switch

---

lib/excoveralls/html.ex

I had an issue the other day where I could not remember where a generated report is being saved to. So I figured it would be useful to print the file location after successful generation.

Display path to HTML report after generation

---

lib/excoveralls/stats.ex

When having special character in a file, we had a crash : 
```
(UnicodeConversionError) invalid encoding starting at <<161, 41, 32, 45, 62, 32, 36, 105, 59, 10, 105, 115, 111, 95, 116, 111, 95, 97, 115, 99, 105, 105, 40, 36, 162, 41, 32, 45, 62, 32, 36, 99, 59, 10, 105, 115, 111, 95, 116, 111, 95, 97, 115, 99, 105, 105, 40, 36, 163, 41, ...>>
(elixir) lib/string.ex:2154: String.to_charlist/1
lib/excoveralls/stats.ex:106: ExCoveralls.Stats.count_lines/1
lib/excoveralls/stats.ex:64: anonymous fn/2 in ExCoveralls.Stats.generate_coverage/1
(elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
(elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
lib/excoveralls/stats.ex:29: ExCoveralls.Stats.report/1
lib/excoveralls.ex:39: ExCoveralls.execute/2
(mix) lib/mix/tasks/test.ex:390: …
```

Fix UnicodeConversionError and faster count_line

---

lib/excoveralls/stats.ex

Just  a minor spelling fix I came across while looking at source code.

fix spelling on doc for ExCoveralls.Stats.report/1

---

README.md
lib/excoveralls/ignore.ex
lib/excoveralls/stats.ex
test/ignore_test.exs

This pull request addresses issue #177. 
The approach is inspired by the stop-words implementation and ignores all code between `#coveralls-ignore-start` and `#coveralls-ignore-stop` in the coverage calculation
It might not be the most beautiful solution but it helps us a great deal to reach [100% test coverage](https://reflectoring.io/100-percent-test-coverage/).

Ignore lines between coveralls-ignore-start and coveralls-ignore-stop comments

---

lib/excoveralls/ignore.ex
lib/excoveralls/stats.ex

For 0.11.1 version, we will see these compiling warning:
```
==> excoveralls
Compiling 24 files (.ex)
warning: variable "sth" is unused (if the variable is not meant to be used, prefix it with an underscore)
lib/excoveralls/ignore.ex:47
warning: function string_to_charlist/1 is unused
lib/excoveralls/stats.ex:227
```
The unused `string_to_charlist/1` change was made from this commit https://github.com/parroty/excoveralls/commit/a059e4220ef08b097a238783d19f0f7871ed9c75
This PR is to clean these warning, please review.

Clean compiling warning

---

README.md

The heading `Ignore Lines` didn't render properly.

Fix header formatting on the README

---

README.md

Mix gives a warning for quoting keywords when they are not required. Fixing this in the example should prevent downstream project from getting this warning when compiling.

Remove unnecessary quoted keyword from README

---

README.md

It wasn't clear that it's possible to disable shell output for HTML and JSON tasks. I had assumed that it wasn't, and was planning to try to implement it and submit a PR, but having discovered the undocumented option I have updated the README to mention it instead.

Add notes about disabling shell output

---

lib/excoveralls/html.ex
lib/excoveralls/json.ex

When attempting to run `mix coveralls -o public/cover` to generate coverage docs for usage in GitLab pages I get the following error: `** (File.Error) could not make directory "./public/cover": no such file or directory`
By simply adding the -p options to `mkdir` this ceases to be a problem. Hence I switched both `File.mkdir!/1` calls to `File.mkdir_p!/1`

Update path creation/handling for artifacts

---

lib/excoveralls/cover.ex

log error instead of crashes like this
```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
The following arguments were given to IO.chardata_to_string/1:
nil
Attempted function clauses (showing 2 out of 2):
def chardata_to_string(+string+) when -is_binary(string)-
def chardata_to_string(+list+) when -is_list(list)-
(elixir) lib/io.ex:557: IO.chardata_to_string/1
(elixir) lib/file.ex:214: File.exists?/2
(excoveralls) lib/excoveralls/cover.ex:43: ExCoveralls.Cover.has_compile_info?/1
(elixir) lib/enum.ex:2942: Enum.filter_list/2
(elixir) lib/enum.ex:2943: Enum.filter_list/2
(excoveralls) lib/excoveralls.ex:39: ExCoveralls.execute/2
(mix) lib/mix/tasks/test.ex:446: Mix.Tasks.Test.do_run/3
(mix) lib/mix/task.ex:331: Mix.Task.run_task/3
(excoveralls) …
```

remove UndefinedFunctionError requirement for logging missing source error

---

README.md
lib/excoveralls.ex
lib/excoveralls/settings.ex
lib/excoveralls/xml.ex
lib/mix/tasks.ex
test/xml_test.exs

This PR is to add the command `mix coveralls.xml`
The generated file can then be used in quality software like SonarQube (https://www.sonarqube.org/)

Add support to generate XML files

---

lib/excoveralls/poster.ex
test/poster_test.exs

Updated the poster to accept either `:timeout` or `:connect_timeout` as a timeout issue (and therefore don't fail the build) and its corresponding test to also mock that case.

Fix build failure due to `:connect_timeout` from poster

---

lib/excoveralls/poster.ex

This fixes an exception you'd get if the error reason is something more
complicated than an atom or string. For example:
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}} of type Tuple. This protocol is implemented for the following type(s): Time, NaiveDateTime, List, Version, Atom, URI, DateTime, Integer, Date, BitString, Float, Version.Requirement
(elixir 1.10.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir 1.10.3) lib/string/chars.ex:22: String.Chars.to_string/1
lib/excoveralls/poster.ex:58: ExCoveralls.Poster.send_file/2
lib/excoveralls/poster.ex:13: ExCoveralls.Poster.execute/2
(mix 1.10.3) lib/mix/tasks/test.ex:484: Mix.Tasks.Test.do_run/3
(mix 1.10.3) lib/mix/task.ex:330: …
```

Fix error reason message

---

lib/excoveralls/cover.ex
test/cover_test.exs

Currently, elixir modules mocked using the [meck](https://github.com/eproxus/meck) library may leave a trace in the modules list that `excoveralls` tries to cover which won't have a `source` key. As mocks, It is expected that those modules wouldn't have a corresponding source file, but `excoveralls` currently doesn't handle this case. This pull request addresses this issue by improving the bypass logic of modules without a source file.
```elixir
[
version: '7.4',
options: [:no_spawn_compiler_process, :from_core, :no_auto_import],
source: '/Users/diogo.martins/dev/excoveralls/test_missing.ex'
]
```
```elixir
[version: '7.4', options: []]
```
The mocked module scenario starts breaking when whe assume that every module has a `:source` at `Keyword.get(info, :source)`. It returns `nil` and …

Fixing mocked modules coverage handling

---

lib/excoveralls/circle.ex

In our experience using `mix coveralls.circle --parallel --umbrella` the parallel jobs are reported using a duplicate `service_job_id`. I've added the `CIRCLE_NODE_INDEX` as suggested on the main Coveralls repository at https://github.com/lemurheavy/coveralls-public/issues/1341#issuecomment-611676566.
I am not sure if this is backwards incompatible for older CircleCI users, might be good for them to test this and chime in as well.

Fix issue with CircleCI parallel workflows not picking up separate builds

---

lib/templates/html/htmlcov/_style.html.eex

When working on a large project with many deeply-nested files, scanning the list of files for a particular one is difficult because of the right-alignment. This change makes the file paths line up so you can quickly tell when you're looking at a different folder. The coverage percentage remains right-aligned, so that is still easy to scan.

Remove `text-align: right` so filenames are easier to scan

---

README.md

Hey, thanks for excoveralls! I found this invalid reference link in the README.

Fix a reference link on README

---

lib/excoveralls.ex
mix.exs

Fixing warnings like:
```shell
warning: redefining @doc attribute previously set at line x.
warning: EEx.eval_file/2 defined in application :eex is used by the current application but the current application does not directly depend on :eex.
warning: :cover.analyse/3 defined in application :tools is used by the current application but the current application does not directly depend on :tools.
```

fix-warnings-elixir1.11

---

README.md

Explain that skip_files should be valid elixir regexes

---

lib/excoveralls.ex
lib/excoveralls/gitlab.ex
lib/mix/tasks.ex
test/excoveralls_test.exs
test/gitlab_test.exs
test/mix/tasks_test.exs

Hi there, 
I see the example uses the native coverage of GitLab.
I would like to use coveralls though because of the parallel feature.
What do you think? Would it make sense to add that?
Cheers

Add a task to upload coverage from gitlab

---

.github/workflows/tests.yml

They have bumped the action/cache repo to v2, should probably start using it.

bumping cache action to v2

---

.github/workflows/tests.yml

For avoiding error with `runs-on: ubuntu-latest` runner.

Update OTP version for github actions

---

README.md
lib/excoveralls/post.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
test/mix/tasks_test.exs
test/post_test.exs

Hi @parroty ,
This change tries to support the following options for `mix coveralls.post`:
1. parallel 
2. service_number 
3. git hub root directory path
4. git hub sub directory path
We use Jenkins, but since it's not directly supported by excoveralls, we are using `mix coveralls.post`.
For git hub root/sub directory path options, we have a repository that has multiple umbrella projects, and would like to specify different subdirectories for each umbrella project. When we send multiple posts within the same build for multiple umbrella projects, these options can be useful (before source files were not shown because of missing paths unless we put the path manually on UI).
Please let me know if this makes sense. If it does, I'll add more unit tests or documents, and try to finish this …

Add options to post

---

.github/workflows/tests.yml
README.md

Erlef already changed the package name from setup-elixir to setup-beam. This commit updates the workflow and also documents so that they're up-to-date.

Use the latest setup beam for Github action

---

README.md
lib/excoveralls.ex
lib/excoveralls/lcov.ex
lib/mix/tasks.ex
test/lcov_test.exs

https://github.com/parroty/excoveralls/issues/104
The following are supported.
* `TN` empty
* `SF` name
* `DA`  line , execution count
* `LH`
* `LF`
* `end_of_record`

featue: minimum support for lcov

---

README.md
lib/excoveralls/path_reader.ex
test/mix/path_reader_test.exs

This patch changes the `PathReader.base_path` function to try reading
from the `Application` first, using the current method as a fallback
mechanism in case the config is not available.
The reason for this change is that we want to instrument a running
elixir app while executing some acceptance tests and
`Mix.Project.config_files` does not have all the necessary information
to infer the path.

chore: PathReader.base_path config

---

README.md
lib/excoveralls/html.ex
lib/templates/html/htmlcov/coverage.html.eex
test/html_test.exs

I find it useful to focus on files not fully covered so I added an option for HTML reports that allows hiding all fully covered files.
This is only a proposal and some open points/missing things remain to be done but I would like to know your opinion before actually implement all of them.
I know that I can copy the `eex` template on my repo and add the needed if clause to obtain this behavior but I think this can be useful to other people.
Open points
- Should I add a disclaimer on the generated HTML that says that fully covered files are hidden?
- When this option is true should I hide the same files also from the terminal report?
- Test are still missing

Add option for filtering out full covered files from HTML report

---

lib/excoveralls/poster.ex
test/poster_test.exs

PR adds a special behaviour to the logic for uploading coverage reports that can survive the outage and maintenance of the remote UI (e.g. was the case for [coveralls](https://coveralls.io/)). I am not sure if it would be better to make this behaviour configurable, but in our case, it resulted in failing our PR within CI. Let me know if it makes sense and/or suggestions for improvement.

Survive coveralls maintenance and outagle

---

README.md

Refer to #284 and #239 for the backgrounds.

Update README with instructions on silencing OTP warnings

---

CHANGELOG.md
test/mix/tasks_test.exs

Hi,
I have noticed a small typo and created a PR to fix it.
Also capture extra output from tests.

Fix typo and capture extra output from tests

---

README.md
lib/excoveralls/circle.ex
lib/excoveralls/drone.ex
lib/excoveralls/github.ex
lib/excoveralls/gitlab.ex
lib/excoveralls/post.ex
lib/excoveralls/semaphore.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
test/mix/tasks_test.exs
test/post_test.exs

We think flag_name is a nice addition to the payload, given that it's a very good organisation tool to sort out your coveralls in groups. Or just get them tagged with anything you want in general for grouping purposes.

Allows flag_name to pass thru to the coveralls.io API

---

lib/excoveralls/cover.ex
test/cover_test.exs

I would like to propose more granular logging for the case when module's source file does not exist.
Recently we faced the issue with our CI sometimes producing wrong reports.
All compiled `.beam` files store the absolute path to the source of the module (which is accessed via `module_info`). We use `GitLab` for our CI and by default it checkout the source code with the following pattern:
```
{builds_dir}/$RUNNER_TOKEN_KEY/$CONCURRENT_ID/$NAMESPACE/$PROJECT_NAME
```
From one runner to another the absolute path is different. With caching in place new runner was pointing to the wrong address (which was correct on other machine).
There is nothing wrong with the library itself but I believe more explicit logging message would've helped us to spot the issue faster.
_Initially, I made a wrong …

Improve logging for a case with the missing source file

---

README.md
lib/excoveralls.ex
mix.exs

The command `mix test --cover --export-coverage XXX` exports the coverage data when using the default coverage tool of Elixir, but does not export anything when ExCoveralls is in use. This PR fixes this behavior.  It makes ExCoverall work just like the standard Elixir tool.

add .coverdata file export

---

README.md
lib/excoveralls.ex
lib/excoveralls/cover.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
test/mix/tasks_test.exs

This PR aims to handle the generation and import of coverage data.
For generation, we need to handle the `:export` and `:output` options given to `ExCoveralls.start/2` function. These options are described in Mix documentation for [test.coverage](https://hexdocs.pm/mix/1.14.1/Mix.Tasks.Test.Coverage.html#module-exporting-coverage).
For import, I added a new command line option (`--import-cover`) for selecting a directory from where cover data should be loaded. These files will be imported after module cover-compilation and their data will be added to the generated report.

Import coverdata if needed

---

lib/excoveralls.ex
lib/excoveralls/conf_server.ex
lib/excoveralls/local.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
test/html_test.exs
test/json_test.exs
test/lcov_test.exs
test/local_test.exs
test/mix/tasks_test.exs
test/xml_test.exs

This allows running multiple coveralls tasks at once without re-running all the tests.
Before:
```
mix coveralls.html
mix coveralls.json
```
After:
```
mix coveralls.multiple --type html --type json
```

Add coveralls.multiple command

---

README.md
lib/excoveralls/ignore.ex
test/ignore_test.exs

Allows to ignore the coverage for the following line of code, by putting a new type of comment `# coveralls-ignore-next-line`.
Ignoring a single line is a common use case, which currently can be done by wrapping the code between the "start" and "stop" comments. If we can achieve the same with just one comment, this produces less visual noise and leaves more space for the useful code.
Resolves #219

Ignore single next line

---

lib/excoveralls.ex
lib/excoveralls/cobertura.ex
lib/excoveralls/task/util.ex
lib/mix/tasks.ex
mix.exs
mix.lock
test/cobertura_test.exs
test/mix/tasks_test.exs

A taks is added for generating XML [Cobertura](https://cobertura.github.io/cobertura/) reports
This is useful for instance to enable the [Test coverage visualization](https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html) feature of GitLab.

cobertura task

---

lib/excoveralls/cobertura.ex
test/cobertura_test.exs

A protocol  (`defprotocol`) or implementation (`defimpl`) definition covered during the tests triggers an error when using the cobertura formatter.
This PR fixes it.
<details>
<summary>
```
** (MatchError) no match of right hand side value: nil
(excoveralls 0.16.0) lib/excoveralls/cobertura.ex:168: ExCoveralls.Cobertura.module_name/1
```
</summary>
```
(excoveralls 0.16.0) lib/excoveralls/cobertura.ex:99: anonymous fn/3 in ExCoveralls.Cobertura.generate_packages/2
(elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
(excoveralls 0.16.0) lib/excoveralls/cobertura.ex:97: ExCoveralls.Cobertura.generate_packages/2
(excoveralls 0.16.0) lib/excoveralls/cobertura.ex:74: ExCoveralls.Cobertura.generate_xml/2
(excoveralls 0.16.0) lib/excoveralls/cobertura.ex:16: …
```

Cobertura now handles defprotocol and defimpl definitions

---

lib/excoveralls/lcov.ex
test/lcov_test.exs

Prior to 2.0 being released, `genhtml` was much better about handling  source files from the following paths:
* `test/support/some_helper.ex`
* `lib/foo/bar.ex`
But after 2.0 was released, when rendering with `genhtml` the paths  would be mangled and look like the following:
* `test/support/test/support/some_helper.ex`
* `lib/foo/lib/foo/bar.ex`
I have tried in vain with many permutations of `--prefix` when running `genhtml` but the ultimate fix that made all of this go away was using the absolute path for the source file (`SF`).

Fix lcov 2.0 source file handling

---

README.md
lib/excoveralls.ex
lib/excoveralls/task/util.ex

Hi friends! Thanks for such a great tool.
This PR adds additional documentation/usage for the `--import-cover` flag and makes a change that improves the ergonomics of integration test coverage.
* `.coverdata` is now imported just before `ExCoveralls.execute/3`, instead of during `ExCoveralls.start/2`. This allows coverage data generated during the test run to be included in the final report.
* Fixed a small error in documentation: `--import_cover` -> `--import-cover`
* Added a new section to the README with additional explanation and an example of `--import-cover` usage.
/cc @albertored, who first introduced this feature

Import `.coverdata` after test run and improve documentation

---

README.md
lib/excoveralls/poster.ex
test/poster_test.exs

Hi there 👋
With this PR, excoveralls allows passing custom http options.
This is useful for example when you have `castore` installed, but need to specify a different `cacertfile`.

Accept custom http options

---

README.md
lib/conf/coveralls.json
lib/excoveralls/local.ex
lib/excoveralls/settings.ex
lib/excoveralls/stats.ex
test/html_test.exs
test/local_test.exs
test/poster_test.exs
test/stats_test.exs

We do not want to report a 100% coverage when there are lines that are not covered.

Always floor coverage instead of rounding

---

lib/excoveralls/cobertura.ex

Since Elixir v1.16 negative slices (steps) to `String.slice/2` have been deprecated and throws a warning for each call when running `mix coveralls.cobertura`.
Example warning:
> warning: negative steps are not supported in String.slice/2, pass 31..-1//1 instead
This PR removes the warning by using explicit steps as the warning message recommends. However since this library supports also v1.11, which does not support explicit steps yet, this PR conditionally calls `Range.new/3` instead of using `x..y//step`. Otherwise we would get a syntax error during compilation on v.1.11.
Let me know if there is anything else that needs to be done in this PR.

Use explicit steps to remove 1.16 deprecation warning in Cobertura

---

CHANGELOG.md
lib/excoveralls/circle.ex
lib/excoveralls/drone.ex
lib/excoveralls/github.ex
lib/excoveralls/gitlab.ex
lib/excoveralls/ignore.ex
lib/excoveralls/json.ex
lib/excoveralls/local.ex
lib/excoveralls/post.ex
lib/excoveralls/semaphore.ex
lib/excoveralls/stats.ex
lib/excoveralls/travis.ex
test/circle_test.exs
test/cobertura_test.exs
test/drone_test.exs
test/github_test.exs
test/gitlab_test.exs
test/html_test.exs
test/ignore_test.exs
test/json_test.exs
test/lcov_test.exs
test/local_test.exs
test/post_test.exs
test/semaphore_test.exs
test/travis_test.exs
test/xml_test.exs

This PR addresses the issue of [accidentally ignoring too much code coverage](https://github.com/parroty/excoveralls/issues/197). The issue happens when you add `coveralls-ignore-start` but forget to add the corresponding `-ignore-stop`. With this change, excoveralls is going to discard the un-closed ignore-block (i.e. not ignore the coverage) and give you a warning, so that you can more easily spot the mistake.
Besides the main goal, this change also adds a few other useful warnings to let you know about redundant or invalid ignore-comments, which I [previously outlined](https://github.com/parroty/excoveralls/issues/197#issuecomment-1979244971). This is an optional part, and we could remove it or split it into a separate PR if that would be more appropriate.
The most interesting part for …

Detect and warn about incorrectly used ignore-comments

---

lib/excoveralls/cobertura.ex

Without this change, the output is full of warnings such as
```
warning: negative steps are not supported in String.slice/2, pass 44..-1//1 instead
```

add missing step for Cobertura's range

---

lib/excoveralls/cobertura.ex

Reverts parroty/excoveralls#329 due to following errors.
```
== Compilation error in file lib/excoveralls/cobertura.ex ==
Error: ** (SyntaxError) lib/excoveralls/cobertura.ex:191:87: syntax error before: '/'
(elixir 1.11.4) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
Error: Process completed with exit code 1.
```

Revert "add missing step for Cobertura's range"

---

.github/workflows/tests.yml
lib/excoveralls/cobertura.ex
test/settings_test.exs

the inline syntax fails with elixir 1.11
I've also added elixir 1.17 to the matrix, as the tests were failing in that version due to some path resolution difference between 1.15 and 1.16
Closes #331 
Follow up to #329

Update Range to use function syntax

---

lib/excoveralls/stop_words.ex

When using excoveralls with elixir `main`, the following error is produced:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {"defmodule Test do", nil} of type Tuple. This protocol is implemented for the following type(s): Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
```
This is because we provide a list of tuples, but that is not valid according to the typespec `@spec zip([list()]) :: [tuple()]`. 
Since Elixir is deprecating `List.zip/1`, the code was slightly changed and a list of tuples is no longer accepted.
This PR switches to `Enum.zip/1`, and uses a list of lists instead of tuples. That should be compatible since Elixir 1.4 and avoid upcoming deprecations.

Elixir 1.18 compatibility

---

README.md
lib/excoveralls.ex
lib/excoveralls/json.ex
test/json_test.exs

When running an umbrella app's coveralls in partitioned instances - a way to specify reports is needed for tools like CodeCov to [merge reports](https://docs.codecov.com/docs/github-4a-merging-reports) - this is helpful when running GH actions as a matrix for each app, or even if running the same app in partitions.
Leverage the same `export` flag that exists for `.coverdata` files and allow the name to be used instead of the hardcoded `excoveralls.json` if it exists. That way predictable filenames can be given and default behaviour preserved.

Add Custom Filename support for coveralls.json
